# Generated by Django 5.0.3 on 2024-03-27 07:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carversal", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="horsepower",
            field=models.IntegerField(default=180),
        ),
        migrations.AddField(
            model_name="car",
            name="mileage",
            field=models.IntegerField(default=8),
        ),
    ]
