# Generated by Django 5.0.3 on 2024-03-27 13:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carversal", "0002_car_horsepower_car_mileage"),
    ]

    operations = [
        migrations.AddField(
            model_name="car",
            name="Car_make",
            field=models.CharField(default="", max_length=50),
        ),
    ]
