# Generated by Django 5.0.3 on 2024-03-27 19:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carversal", "0003_car_car_make"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="bodytype",
            new_name="style",
        ),
    ]
