# Generated by Django 5.0.3 on 2024-03-27 20:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carversal", "0004_rename_bodytype_car_style"),
    ]

    operations = [
        migrations.RenameField(
            model_name="car",
            old_name="Car_make",
            new_name="make",
        ),
        migrations.RenameField(
            model_name="car",
            old_name="Car_name",
            new_name="model",
        ),
    ]
