# Generated by Django 5.0.3 on 2024-04-11 08:22

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("carversal", "0007_alter_car_price_cartitem"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="car_id",
            new_name="product",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="car_model",
        ),
        migrations.RemoveField(
            model_name="cartitem",
            name="pre_booking_price",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="date_added",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="user",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="cartitem",
            name="quantity",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
