# Generated by Django 5.0.3 on 2024-04-11 08:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("carversal", "0008_rename_car_id_cartitem_product_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartitem",
            old_name="product",
            new_name="car",
        ),
    ]
